<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    public function run(): void
    {
        $customers = [
            [
                'code' => 'CUST-001',
                'company_name' => 'PT Maju Jaya Abadi',
                'customer_type' => 'company',
                'email' => 'info@maju-jaya.co.id',
                'phone' => '081234567890',
                'city' => 'Jakarta',
                'state' => 'DKI Jakarta',
                'postal_code' => '12950',
                'credit_limit' => 500000000,
                'payment_terms' => 'Net 30',
                'is_active' => true,
                'registered_at' => '2023-01-15',
            ],
            [
                'code' => 'CUST-002',
                'company_name' => 'CV Karya Mandiri Sejahtera',
                'customer_type' => 'company',
                'email' => 'karya.mandiri@email.com',
                'phone' => '081345678901',
                'city' => 'Surabaya',
                'state' => 'Jawa Timur',
                'postal_code' => '60115',
                'credit_limit' => 250000000,
                'payment_terms' => 'Net 30',
                'is_active' => true,
                'registered_at' => '2023-02-20',
            ],
            [
                'code' => 'CUST-003',
                'company_name' => 'PT Indah Jaya Makmur',
                'customer_type' => 'company',
                'email' => 'indahjaya@yahoo.com',
                'phone' => '081456789012',
                'city' => 'Bandung',
                'state' => 'Jawa Barat',
                'postal_code' => '40115',
                'credit_limit' => 350000000,
                'payment_terms' => 'Net 45',
                'is_active' => true,
                'registered_at' => '2023-03-10',
            ],
            [
                'code' => 'CUST-004',
                'company_name' => 'CV Sinar Jaya Teknik',
                'customer_type' => 'company',
                'email' => 'sinarjaya.teknik@gmail.com',
                'phone' => '081567890123',
                'city' => 'Medan',
                'state' => 'Sumatera Utara',
                'postal_code' => '20112',
                'credit_limit' => 150000000,
                'payment_terms' => 'Net 30',
                'is_active' => true,
                'registered_at' => '2023-04-05',
            ],
            [
                'code' => 'CUST-005',
                'company_name' => 'PT Bumi Raya Perkasa',
                'customer_type' => 'company',
                'email' => 'bumiraya@perkasa.co.id',
                'phone' => '081678901234',
                'city' => 'Semarang',
                'state' => 'Jawa Tengah',
                'postal_code' => '50111',
                'credit_limit' => 200000000,
                'payment_terms' => 'Net 30',
                'is_active' => true,
                'registered_at' => '2023-05-12',
            ],
            [
                'code' => 'CUST-006',
                'company_name' => 'UD Sumber Rejeki',
                'customer_type' => 'company',
                'email' => 'sumber.rejeki@email.com',
                'phone' => '081789012345',
                'city' => 'Yogyakarta',
                'state' => 'DI Yogyakarta',
                'postal_code' => '55111',
                'credit_limit' => 100000000,
                'payment_terms' => 'Cash',
                'is_active' => true,
                'registered_at' => '2023-06-18',
            ],
            [
                'code' => 'CUST-007',
                'company_name' => 'PT Kencana Sakti',
                'customer_type' => 'company',
                'email' => 'kencana.sakti@email.com',
                'phone' => '081890123456',
                'city' => 'Makassar',
                'state' => 'Sulawesi Selatan',
                'postal_code' => '90111',
                'credit_limit' => 180000000,
                'payment_terms' => 'Net 60',
                'is_active' => true,
                'registered_at' => '2023-07-22',
            ],
            [
                'code' => 'CUST-008',
                'company_name' => 'CV Agung Perdana',
                'customer_type' => 'company',
                'email' => 'agung.perdana@yahoo.com',
                'phone' => '081901234567',
                'city' => 'Denpasar',
                'state' => 'Bali',
                'postal_code' => '80111',
                'credit_limit' => 120000000,
                'payment_terms' => 'Net 30',
                'is_active' => true,
                'registered_at' => '2023-08-30',
            ],
            [
                'code' => 'CUST-009',
                'company_name' => 'PT Nusantara Indah',
                'customer_type' => 'company',
                'email' => 'nusantara.indah@email.com',
                'phone' => '082012345678',
                'city' => 'Palembang',
                'state' => 'Sumatera Selatan',
                'postal_code' => '30111',
                'credit_limit' => 160000000,
                'payment_terms' => 'Net 30',
                'is_active' => true,
                'registered_at' => '2023-09-14',
            ],
            [
                'code' => 'CUST-010',
                'company_name' => 'Toko Mesin Jaya',
                'customer_type' => 'company',
                'email' => 'tokomesinjaya@gmail.com',
                'phone' => '082123456789',
                'city' => 'Jakarta',
                'state' => 'DKI Jakarta',
                'postal_code' => '10710',
                'credit_limit' => 50000000,
                'payment_terms' => 'COD',
                'is_active' => true,
                'registered_at' => '2023-10-01',
            ],
            [
                'code' => 'CUST-011',
                'company_name' => 'PT Sinar Abadi Sejahtera',
                'customer_type' => 'company',
                'email' => 'sinarabadi@email.com',
                'phone' => '082234567890',
                'city' => 'Bekasi',
                'state' => 'Jawa Barat',
                'postal_code' => '17111',
                'credit_limit' => 300000000,
                'payment_terms' => 'Net 45',
                'is_active' => true,
                'registered_at' => '2023-11-05',
            ],
            [
                'code' => 'CUST-012',
                'company_name' => 'CV Bintang Timur',
                'customer_type' => 'company',
                'email' => 'bintangtimur@yahoo.com',
                'phone' => '082345678901',
                'city' => 'Batam',
                'state' => 'Kepulauan Riau',
                'postal_code' => '29411',
                'credit_limit' => 130000000,
                'payment_terms' => 'Net 30',
                'is_active' => true,
                'registered_at' => '2023-12-10',
            ],
            [
                'code' => 'CUST-013',
                'company_name' => 'PT Karya Agung',
                'customer_type' => 'company',
                'email' => 'karya.agung@email.com',
                'phone' => '082456789012',
                'city' => 'Tangerang',
                'state' => 'Banten',
                'postal_code' => '15111',
                'credit_limit' => 220000000,
                'payment_terms' => 'Net 30',
                'is_active' => true,
                'registered_at' => '2024-01-20',
            ],
            [
                'code' => 'CUST-014',
                'company_name' => 'UD Berkah Barokah',
                'customer_type' => 'company',
                'email' => 'berkahbarokah@gmail.com',
                'phone' => '082567890123',
                'city' => 'Bogor',
                'state' => 'Jawa Barat',
                'postal_code' => '16111',
                'credit_limit' => 75000000,
                'payment_terms' => 'Cash',
                'is_active' => true,
                'registered_at' => '2024-02-15',
            ],
            [
                'code' => 'CUST-015',
                'company_name' => 'PT Mandiri Sukses',
                'customer_type' => 'company',
                'email' => 'mandiri.sukses@email.com',
                'phone' => '082678901234',
                'city' => 'Surabaya',
                'state' => 'Jawa Timur',
                'postal_code' => '60125',
                'credit_limit' => 280000000,
                'payment_terms' => 'Net 45',
                'is_active' => true,
                'registered_at' => '2024-03-01',
            ],
            [
                'code' => 'CUST-016',
                'company_name' => 'CV Karya Indah',
                'customer_type' => 'company',
                'email' => 'karya.indah@email.com',
                'phone' => '082789012345',
                'city' => 'Bandung',
                'state' => 'Jawa Barat',
                'postal_code' => '40125',
                'credit_limit' => 90000000,
                'payment_terms' => 'Net 30',
                'is_active' => true,
                'registered_at' => '2024-03-20',
            ],
            [
                'code' => 'CUST-017',
                'company_name' => 'PT Surya Agung Perkasa',
                'customer_type' => 'company',
                'email' => 'suryaagung@perkasa.com',
                'phone' => '082890123456',
                'city' => 'Medan',
                'state' => 'Sumatera Utara',
                'postal_code' => '20122',
                'credit_limit' => 200000000,
                'payment_terms' => 'Net 60',
                'is_active' => true,
                'registered_at' => '2024-04-10',
            ],
            [
                'code' => 'CUST-018',
                'company_name' => 'Toko Teknik Jaya',
                'customer_type' => 'company',
                'email' => 'teknikjaya@gmail.com',
                'phone' => '082901234567',
                'city' => 'Semarang',
                'state' => 'Jawa Tengah',
                'postal_code' => '50121',
                'credit_limit' => 40000000,
                'payment_terms' => 'COD',
                'is_active' => true,
                'registered_at' => '2024-05-05',
            ],
            [
                'code' => 'CUST-019',
                'company_name' => 'PT Cipta Karya Mandiri',
                'customer_type' => 'company',
                'email' => 'ciptakarya@mandiri.co.id',
                'phone' => '083012345678',
                'city' => 'Makassar',
                'state' => 'Sulawesi Selatan',
                'postal_code' => '90122',
                'credit_limit' => 170000000,
                'payment_terms' => 'Net 30',
                'is_active' => true,
                'registered_at' => '2024-06-12',
            ],
            [
                'code' => 'CUST-020',
                'company_name' => 'CV Maju Bersama',
                'customer_type' => 'company',
                'email' => 'maju.bersama@email.com',
                'phone' => '083123456789',
                'city' => 'Jakarta',
                'state' => 'DKI Jakarta',
                'postal_code' => '12960',
                'credit_limit' => 250000000,
                'payment_terms' => 'Net 30',
                'is_active' => true,
                'registered_at' => '2024-07-01',
            ],
        ];

        foreach ($customers as $data) {
            Customer::firstOrCreate(
                ['code' => $data['code']],
                [
                    'company_name' => $data['company_name'],
                    'customer_type' => $data['customer_type'],
                    'email' => $data['email'],
                    'phone' => $data['phone'],
                    'city' => $data['city'],
                    'state' => $data['state'],
                    'postal_code' => $data['postal_code'],
                    'country' => 'Indonesia',
                    'credit_limit' => $data['credit_limit'],
                    'payment_terms' => $data['payment_terms'],
                    'is_active' => $data['is_active'],
                    'registered_at' => $data['registered_at'],
                    'billing_address' => json_encode(['street' => 'Jl. Contoh No. 1', 'city' => $data['city'], 'province' => $data['state'], 'postal_code' => $data['postal_code']]),
                    'shipping_address' => json_encode(['street' => 'Jl. Contoh No. 1', 'city' => $data['city'], 'province' => $data['state'], 'postal_code' => $data['postal_code']]),
                ]
            );
        }
    }
}
