<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\Unit;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $brandIds = Brand::pluck('id', 'slug')->toArray();
        $categoryIds = Category::pluck('id', 'slug')->toArray();
        $unitIds = Unit::pluck('id', 'name')->toArray();

        $products = [
            // Mesin Pengolahan Makanan
            [
                'name' => 'Mesin Penggiling Biji Kopi SG-300',
                'sku' => 'SKU-MKM-001',
                'category_slug' => 'mesin-pengolahan-makanan',
                'brand_slug' => 'indomesin-teknologi',
                'unit' => 'Unit',
                'price' => 3500000,
                'cost_price' => 2450000,
                'selling_price' => 3500000,
                'weight' => 45,
                'width' => 50, 'length' => 60, 'height' => 80,
                'power' => '750 Watt',
                'capacity' => '300 kg/jam',
                'material' => 'Stainless Steel 304',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Mesin penggiling biji kopi kapasitas 300 kg/jam. Cocok untuk industri kopi skala menengah hingga besar. Dilengkapi dengan pengaturan kehalusan hasil gilingan.',
                'short_description' => 'Mesin giling kopi kapasitas 300 kg/jam, stainless steel, garansi 2 tahun',
            ],
            [
                'name' => 'Mesin Roasting Kopi Kapasitas 10kg',
                'sku' => 'SKU-MKM-002',
                'category_slug' => 'mesin-pengolahan-makanan',
                'brand_slug' => 'indomesin-teknologi',
                'unit' => 'Unit',
                'price' => 18500000,
                'cost_price' => 12950000,
                'selling_price' => 18500000,
                'weight' => 120,
                'width' => 90, 'length' => 120, 'height' => 150,
                'power' => '2500 Watt',
                'capacity' => '10 kg/batch',
                'material' => 'Stainless Steel 304',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Mesin roasting kopi kapasitas 10 kg per batch. Dilengkapi kontrol suhu digital dan sistem pendingin cepat.',
                'short_description' => 'Roasting kopi 10kg/batch dengan kontrol digital',
            ],
            [
                'name' => 'Mesin Pembuat Mie Otomatis BM-200',
                'sku' => 'SKU-MKM-003',
                'category_slug' => 'mesin-pengolahan-makanan',
                'brand_slug' => 'foodpack-indo',
                'unit' => 'Unit',
                'price' => 12500000,
                'cost_price' => 8750000,
                'selling_price' => 12500000,
                'weight' => 80,
                'width' => 70, 'length' => 100, 'height' => 130,
                'power' => '1500 Watt',
                'capacity' => '200 kg/jam',
                'material' => 'Stainless Steel',
                'warranty' => 'Garansi 1 Tahun',
                'warranty_period' => 12,
                'description' => 'Mesin pembuat mie otomatis kapasitas 200 kg/jam. Dilengkapi dengan pengatur ketebalan dan lebar mie.',
                'short_description' => 'Pembuat mie otomatis 200kg/jam, mudah dioperasikan',
            ],
            [
                'name' => 'Mesin Mixer Adonan Roti Spiral',
                'sku' => 'SKU-MKM-004',
                'category_slug' => 'mesin-pengolahan-makanan',
                'brand_slug' => 'foodpack-indo',
                'unit' => 'Unit',
                'price' => 8500000,
                'cost_price' => 5950000,
                'selling_price' => 8500000,
                'weight' => 95,
                'width' => 65, 'length' => 85, 'height' => 110,
                'power' => '1500 Watt',
                'capacity' => '50 kg adonan',
                'material' => 'Stainless Steel',
                'warranty' => 'Garansi 1 Tahun',
                'warranty_period' => 12,
                'description' => 'Mixer spiral untuk adonan roti kapasitas 50 kg. Hasil adonan yang sempurna dengan waktu mixing yang efisien.',
                'short_description' => 'Mixer spiral 50kg untuk industri roti dan bakery',
            ],
            [
                'name' => 'Mesin Pengering Gabah Tipe Bakar',
                'sku' => 'SKU-MKM-005',
                'category_slug' => 'mesin-pengolahan-makanan',
                'brand_slug' => 'agromech-solutions',
                'unit' => 'Unit',
                'price' => 45000000,
                'cost_price' => 31500000,
                'selling_price' => 45000000,
                'weight' => 350,
                'width' => 150, 'length' => 300, 'height' => 200,
                'power' => '5000 Watt',
                'capacity' => '5 ton/hari',
                'material' => 'Besi Cor',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Mesin pengering gabah sistem bakar dengan kapasitas 5 ton per hari. Efisien dan hemat bahan bakar.',
                'short_description' => 'Pengering gabah 5 ton/hari, hemat bahan bakar',
            ],
            [
                'name' => 'Mesin Penggiling Daging Industri TC-32',
                'sku' => 'SKU-MKM-006',
                'category_slug' => 'mesin-pengolahan-makanan',
                'brand_slug' => 'indomesin-teknologi',
                'unit' => 'Unit',
                'price' => 5500000,
                'cost_price' => 3850000,
                'selling_price' => 5500000,
                'weight' => 55,
                'width' => 40, 'length' => 60, 'height' => 85,
                'power' => '1100 Watt',
                'capacity' => '200 kg/jam',
                'material' => 'Stainless Steel',
                'warranty' => 'Garansi 1 Tahun',
                'warranty_period' => 12,
                'description' => 'Mesin penggiling daging kapasitas industri 200 kg/jam. Cocok untuk pabrik bakso, sosis, dan olahan daging.',
                'short_description' => 'Giling daging 200kg/jam untuk industri',
            ],
            [
                'name' => 'Mesin Penepung Disk Mill FFC-45',
                'sku' => 'SKU-MKM-007',
                'category_slug' => 'mesin-pengolahan-makanan',
                'brand_slug' => 'agromech-solutions',
                'unit' => 'Unit',
                'price' => 4200000,
                'cost_price' => 2940000,
                'selling_price' => 4200000,
                'weight' => 50,
                'width' => 50, 'length' => 70, 'height' => 100,
                'power' => '2200 Watt',
                'capacity' => '250 kg/jam',
                'material' => 'Besi Cor',
                'warranty' => 'Garansi 1 Tahun',
                'warranty_period' => 12,
                'description' => 'Mesin penepung disk mill untuk berbagai bahan kering seperti beras, jagung, kedelai, dan rempah.',
                'short_description' => 'Penepung serbaguna 250kg/jam untuk bahan kering',
            ],
            [
                'name' => 'Mesin Extruder Makanan Ringan',
                'sku' => 'SKU-MKM-008',
                'category_slug' => 'mesin-pengolahan-makanan',
                'brand_slug' => 'foodpack-indo',
                'unit' => 'Unit',
                'price' => 28000000,
                'cost_price' => 19600000,
                'selling_price' => 28000000,
                'weight' => 200,
                'width' => 100, 'length' => 200, 'height' => 150,
                'power' => '5500 Watt',
                'capacity' => '100 kg/jam',
                'material' => 'Stainless Steel',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Mesin extruder untuk pembuatan makanan ringan seperti snack, chiki, dan produk ekstrusi lainnya.',
                'short_description' => 'Extruder makanan ringan 100kg/jam, multi bentuk',
            ],

            // Mesin Packaging
            [
                'name' => 'Mesin Pengemas Vakum DZ-600',
                'sku' => 'SKU-PKG-001',
                'category_slug' => 'mesin-packaging',
                'brand_slug' => 'foodpack-indo',
                'unit' => 'Unit',
                'price' => 7500000,
                'cost_price' => 5250000,
                'selling_price' => 7500000,
                'weight' => 80,
                'width' => 70, 'length' => 80, 'height' => 100,
                'power' => '900 Watt',
                'capacity' => '300 pack/jam',
                'material' => 'Stainless Steel',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Mesin pengemas vakum untuk produk makanan dengan chamber size 600mm. Ideal untuk pengemasan produk agar tahan lama.',
                'short_description' => 'Vacuum packaging 600mm, 300 pack/jam',
            ],
            [
                'name' => 'Mesin Packaging Vertikal VFFS-500',
                'sku' => 'SKU-PKG-002',
                'category_slug' => 'mesin-packaging',
                'brand_slug' => 'foodpack-indo',
                'unit' => 'Unit',
                'price' => 65000000,
                'cost_price' => 45500000,
                'selling_price' => 65000000,
                'weight' => 400,
                'width' => 120, 'length' => 150, 'height' => 250,
                'power' => '3000 Watt',
                'capacity' => '50 pack/menit',
                'material' => 'Stainless Steel 304',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Mesin packaging vertikal VFFS-500 untuk mengemas produk granular, snack, dan bubuk secara otomatis.',
                'short_description' => 'Vertical packaging otomatis 50 pack/menit',
            ],
            [
                'name' => 'Mesin Strapping Band Otomatis',
                'sku' => 'SKU-PKG-003',
                'category_slug' => 'mesin-packaging',
                'brand_slug' => 'foodpack-indo',
                'unit' => 'Unit',
                'price' => 8500000,
                'cost_price' => 5950000,
                'selling_price' => 8500000,
                'weight' => 60,
                'width' => 60, 'length' => 80, 'height' => 140,
                'power' => '650 Watt',
                'capacity' => '500 siklus/jam',
                'material' => 'Besi',
                'warranty' => 'Garansi 1 Tahun',
                'warranty_period' => 12,
                'description' => 'Mesin strapping band otomatis untuk pengikatan kardus dan paket dengan tali strapping.',
                'short_description' => 'Strapping otomatis 500 siklus/jam',
            ],
            [
                'name' => 'Mesin Shrink Wrap Packaging',
                'sku' => 'SKU-PKG-004',
                'category_slug' => 'mesin-packaging',
                'brand_slug' => 'foodpack-indo',
                'unit' => 'Unit',
                'price' => 9500000,
                'cost_price' => 6650000,
                'selling_price' => 9500000,
                'weight' => 90,
                'width' => 80, 'length' => 100, 'height' => 120,
                'power' => '2000 Watt',
                'capacity' => '200 pack/jam',
                'material' => 'Stainless Steel',
                'warranty' => 'Garansi 1 Tahun',
                'warranty_period' => 12,
                'description' => 'Mesin shrink wrap untuk pengemasan produk dengan plastik shrink. Cocok untuk packaging retail.',
                'short_description' => 'Shrink wrap 200 pack/jam untuk packaging retail',
            ],

            // Mesin Minuman
            [
                'name' => 'Mesin Filling Minuman Sirup',
                'sku' => 'SKU-MNM-001',
                'category_slug' => 'mesin-minuman',
                'brand_slug' => 'foodpack-indo',
                'unit' => 'Unit',
                'price' => 22500000,
                'cost_price' => 15750000,
                'selling_price' => 22500000,
                'weight' => 150,
                'width' => 80, 'length' => 120, 'height' => 180,
                'power' => '1500 Watt',
                'capacity' => '1000 botol/jam',
                'material' => 'Stainless Steel 304',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Mesin filling minuman sirup otomatis untuk botol 250ml - 1000ml. Dilengkapi sistem pengisian presisi.',
                'short_description' => 'Filling sirup 1000 botol/jam, presisi tinggi',
            ],
            [
                'name' => 'Mesin Pembuat Es Kristal 5 Ton',
                'sku' => 'SKU-MNM-002',
                'category_slug' => 'mesin-minuman',
                'brand_slug' => 'powergen-industries',
                'unit' => 'Unit',
                'price' => 350000000,
                'cost_price' => 245000000,
                'selling_price' => 350000000,
                'weight' => 2000,
                'width' => 200, 'length' => 300, 'height' => 250,
                'power' => '25000 Watt',
                'capacity' => '5 ton/hari',
                'material' => 'Stainless Steel 304',
                'warranty' => 'Garansi 3 Tahun',
                'warranty_period' => 36,
                'description' => 'Mesin pembuat es kristal kapasitas 5 ton per hari. Menggunakan sistem refrigerasi industrial yang efisien.',
                'short_description' => 'Ice maker 5 ton/hari untuk industri',
            ],
            [
                'name' => 'Mesin Pasteurisasi Susu',
                'sku' => 'SKU-MNM-003',
                'category_slug' => 'mesin-minuman',
                'brand_slug' => 'biopharm-machinery',
                'unit' => 'Unit',
                'price' => 85000000,
                'cost_price' => 59500000,
                'selling_price' => 85000000,
                'weight' => 500,
                'width' => 120, 'length' => 200, 'height' => 180,
                'power' => '10000 Watt',
                'capacity' => '500 liter/jam',
                'material' => 'Stainless Steel 304',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Mesin pasteurisasi susu kapasitas 500 liter/jam. Dilengkapi sistem kontrol suhu otomatis.',
                'short_description' => 'Pasteurisasi susu 500L/jam, kontrol otomatis',
            ],

            // Mesin Pertanian
            [
                'name' => 'Traktor Tangan Quick G-300',
                'sku' => 'SKU-TAN-001',
                'category_slug' => 'mesin-pertanian',
                'brand_slug' => 'agromech-solutions',
                'unit' => 'Unit',
                'price' => 8500000,
                'cost_price' => 5950000,
                'selling_price' => 8500000,
                'weight' => 75,
                'width' => 60, 'length' => 170, 'height' => 100,
                'power' => '6500 Watt',
                'capacity' => '-',
                'material' => 'Besi Cor',
                'warranty' => 'Garansi 1 Tahun',
                'warranty_period' => 12,
                'description' => 'Traktor tangan serbaguna untuk pengolahan lahan pertanian. Mesin diesel 6.5 HP, mudah dioperasikan.',
                'short_description' => 'Traktor tangan 6.5 HP untuk pengolahan lahan',
            ],
            [
                'name' => 'Mesin Panen Padi Combine Harvester',
                'sku' => 'SKU-TAN-002',
                'category_slug' => 'mesin-pertanian',
                'brand_slug' => 'agromech-solutions',
                'unit' => 'Unit',
                'price' => 185000000,
                'cost_price' => 129500000,
                'selling_price' => 185000000,
                'weight' => 1800,
                'width' => 180, 'length' => 450, 'height' => 250,
                'power' => '25000 Watt',
                'capacity' => '3 ton/jam',
                'material' => 'Besi Cor',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Combine harvester untuk memanen padi secara otomatis. Kapasitas 3 ton/jam, irit bahan bakar.',
                'short_description' => 'Combine harvester 3 ton/jam untuk panen padi',
            ],
            [
                'name' => 'Mesin Penanam Padi Indojaya',
                'sku' => 'SKU-TAN-003',
                'category_slug' => 'mesin-pertanian',
                'brand_slug' => 'agromech-solutions',
                'unit' => 'Unit',
                'price' => 16500000,
                'cost_price' => 11550000,
                'selling_price' => 16500000,
                'weight' => 40,
                'width' => 120, 'length' => 150, 'height' => 80,
                'power' => '3000 Watt',
                'capacity' => '0.5 hektar/jam',
                'material' => 'Besi Cor',
                'warranty' => 'Garansi 1 Tahun',
                'warranty_period' => 12,
                'description' => 'Mesin penanam padi otomatis dengan sistem tanam presisi untuk meningkatkan produktivitas.',
                'short_description' => 'Penanam padi otomatis 0.5 hektar/jam',
            ],

            // Mesin Peternakan
            [
                'name' => 'Mesin Pakan Ternak Pelet Apung',
                'sku' => 'SKU-TRK-001',
                'category_slug' => 'mesin-peternakan',
                'brand_slug' => 'agromech-solutions',
                'unit' => 'Unit',
                'price' => 18500000,
                'cost_price' => 12950000,
                'selling_price' => 18500000,
                'weight' => 120,
                'width' => 80, 'length' => 100, 'height' => 130,
                'power' => '7500 Watt',
                'capacity' => '500 kg/jam',
                'material' => 'Stainless Steel',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Mesin pembuat pakan ternak pelet apung untuk ikan dan udang. Kapasitas 500 kg/jam.',
                'short_description' => 'Pembuat pelet apung 500 kg/jam',
            ],
            [
                'name' => 'Mesin Pencacah Rumput Gajah',
                'sku' => 'SKU-TRK-002',
                'category_slug' => 'mesin-peternakan',
                'brand_slug' => 'agromech-solutions',
                'unit' => 'Unit',
                'price' => 3500000,
                'cost_price' => 2450000,
                'selling_price' => 3500000,
                'weight' => 40,
                'width' => 50, 'length' => 80, 'height' => 100,
                'power' => '3500 Watt',
                'capacity' => '500 kg/jam',
                'material' => 'Besi Cor',
                'warranty' => 'Garansi 1 Tahun',
                'warranty_period' => 12,
                'description' => 'Mesin pencacah rumput gajah dan hijauan pakan ternak. Kapasitas 500 kg/jam.',
                'short_description' => 'Pencacah rumput 500 kg/jam untuk pakan ternak',
            ],
            [
                'name' => 'Mesin Tetas Telur Otomatis 100 Butir',
                'sku' => 'SKU-TRK-003',
                'category_slug' => 'mesin-peternakan',
                'brand_slug' => 'agromech-solutions',
                'unit' => 'Unit',
                'price' => 2800000,
                'cost_price' => 1960000,
                'selling_price' => 2800000,
                'weight' => 15,
                'width' => 45, 'length' => 55, 'height' => 30,
                'power' => '150 Watt',
                'capacity' => '100 butir',
                'material' => 'Plastik & Aluminium',
                'warranty' => 'Garansi 1 Tahun',
                'warranty_period' => 12,
                'description' => 'Mesin tetas telur otomatis kapasitas 100 butir. Dilengkapi pengatur suhu dan kelembaban digital.',
                'short_description' => 'Inkubator telur 100 butir otomatis',
            ],

            // Mesin Perikanan
            [
                'name' => 'Mesin Pembuat Pakan Ikan Apung',
                'sku' => 'SKU-IKN-001',
                'category_slug' => 'mesin-perikanan',
                'brand_slug' => 'agromech-solutions',
                'unit' => 'Unit',
                'price' => 45000000,
                'cost_price' => 31500000,
                'selling_price' => 45000000,
                'weight' => 250,
                'width' => 100, 'length' => 150, 'height' => 180,
                'power' => '15000 Watt',
                'capacity' => '1000 kg/jam',
                'material' => 'Stainless Steel',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Mesin pembuat pakan ikan apung kapasitas 1000 kg/jam. Menghasilkan pelet dengan daya apung tinggi.',
                'short_description' => 'Pakan ikan apung 1000 kg/jam',
            ],
            [
                'name' => 'Pompa Air Tambak 3 Inch',
                'sku' => 'SKU-IKN-002',
                'category_slug' => 'mesin-perikanan',
                'brand_slug' => 'powergen-industries',
                'unit' => 'Unit',
                'price' => 4500000,
                'cost_price' => 3150000,
                'selling_price' => 4500000,
                'weight' => 25,
                'width' => 20, 'length' => 60, 'height' => 25,
                'power' => '750 Watt',
                'capacity' => '500 liter/menit',
                'material' => 'Besi Cor',
                'warranty' => 'Garansi 1 Tahun',
                'warranty_period' => 12,
                'description' => 'Pompa air untuk sirkulasi tambak dan kolam ikan. Debit 500 liter/menit, hemat listrik.',
                'short_description' => 'Pompa tambak 3 inch, 500L/menit',
            ],

            // Boiler
            [
                'name' => 'Boiler Kapasitas 2 Ton B-2000',
                'sku' => 'SKU-BLR-001',
                'category_slug' => 'boiler',
                'brand_slug' => 'powergen-industries',
                'unit' => 'Unit',
                'price' => 350000000,
                'cost_price' => 245000000,
                'selling_price' => 350000000,
                'weight' => 3500,
                'width' => 200, 'length' => 400, 'height' => 300,
                'power' => '15000 Watt',
                'capacity' => '2 ton/jam',
                'material' => 'Carbon Steel',
                'warranty' => 'Garansi 3 Tahun',
                'warranty_period' => 36,
                'description' => 'Boiler kapasitas 2 ton per jam, bahan bakar batubara/biomassa. Dilengkapi sistem kontrol otomatis.',
                'short_description' => 'Boiler 2 ton/jam bahan bakar biomassa',
            ],
            [
                'name' => 'Boiler Steam Kapasitas 5 Ton',
                'sku' => 'SKU-BLR-002',
                'category_slug' => 'boiler',
                'brand_slug' => 'powergen-industries',
                'unit' => 'Unit',
                'price' => 650000000,
                'cost_price' => 455000000,
                'selling_price' => 650000000,
                'weight' => 5500,
                'width' => 250, 'length' => 500, 'height' => 350,
                'power' => '25000 Watt',
                'capacity' => '5 ton/jam',
                'material' => 'Carbon Steel',
                'warranty' => 'Garansi 3 Tahun',
                'warranty_period' => 36,
                'description' => 'Boiler steam kapasitas 5 ton per jam untuk industri menengah. Efisiensi termal tinggi.',
                'short_description' => 'Boiler steam 5 ton/jam untuk industri',
            ],
            [
                'name' => 'Thermic Oil Heater 1 Juta Kkal',
                'sku' => 'SKU-BLR-003',
                'category_slug' => 'boiler',
                'brand_slug' => 'powergen-industries',
                'unit' => 'Unit',
                'price' => 275000000,
                'cost_price' => 192500000,
                'selling_price' => 275000000,
                'weight' => 2800,
                'width' => 180, 'length' => 350, 'height' => 280,
                'power' => '12000 Watt',
                'capacity' => '1.000.000 kkal/jam',
                'material' => 'Carbon Steel',
                'warranty' => 'Garansi 3 Tahun',
                'warranty_period' => 36,
                'description' => 'Thermic oil heater 1 juta kkal per jam untuk aplikasi pemanasan tidak langsung di industri.',
                'short_description' => 'Thermic oil heater 1.000.000 kkal/jam',
            ],

            // Generator
            [
                'name' => 'Generator Diesel 50 KVA',
                'sku' => 'SKU-GEN-001',
                'category_slug' => 'generator',
                'brand_slug' => 'powergen-industries',
                'unit' => 'Unit',
                'price' => 85000000,
                'cost_price' => 59500000,
                'selling_price' => 85000000,
                'weight' => 800,
                'width' => 120, 'length' => 250, 'height' => 150,
                'power' => '50000 Watt',
                'capacity' => '50 KVA',
                'material' => 'Besi',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Generator diesel 50 KVA untuk kebutuhan listrik industri. Mesin diesel Perkins/Doosan.',
                'short_description' => 'Genset diesel 50 KVA untuk industri',
            ],
            [
                'name' => 'Generator Silent 30 KVA',
                'sku' => 'SKU-GEN-002',
                'category_slug' => 'generator',
                'brand_slug' => 'powergen-industries',
                'unit' => 'Unit',
                'price' => 55000000,
                'cost_price' => 38500000,
                'selling_price' => 55000000,
                'weight' => 450,
                'width' => 90, 'length' => 200, 'height' => 120,
                'power' => '30000 Watt',
                'capacity' => '30 KVA',
                'material' => 'Besi',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Generator silent 30 KVA dengan cabin peredam suara. Cocok untuk perkantoran dan rumah sakit.',
                'short_description' => 'Genset silent 30 KVA, rendah kebisingan',
            ],
            [
                'name' => 'Generator Bensin 5000 Watt',
                'sku' => 'SKU-GEN-003',
                'category_slug' => 'generator',
                'brand_slug' => 'powergen-industries',
                'unit' => 'Unit',
                'price' => 7500000,
                'cost_price' => 5250000,
                'selling_price' => 7500000,
                'weight' => 60,
                'width' => 50, 'length' => 70, 'height' => 55,
                'power' => '5000 Watt',
                'capacity' => '5000 Watt',
                'material' => 'Aluminium',
                'warranty' => 'Garansi 1 Tahun',
                'warranty_period' => 12,
                'description' => 'Generator bensin 5000 Watt portabel untuk kebutuhan darurat dan usaha kecil.',
                'short_description' => 'Genset bensin 5000W portabel',
            ],

            // Conveyor
            [
                'name' => 'Conveyor Belt Industri',
                'sku' => 'SKU-CNV-001',
                'category_slug' => 'conveyor',
                'brand_slug' => 'indomesin-teknologi',
                'unit' => 'Set',
                'price' => 45000000,
                'cost_price' => 31500000,
                'selling_price' => 45000000,
                'weight' => 500,
                'width' => 60, 'length' => 1000, 'height' => 80,
                'power' => '3000 Watt',
                'capacity' => '5 ton/jam',
                'material' => 'Besi & Karet',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Conveyor belt untuk material handling industri. Panjang 10 meter, lebar 60 cm.',
                'short_description' => 'Conveyor belt 10m untuk material handling',
            ],
            [
                'name' => 'Conveyor Screw Pengangkut',
                'sku' => 'SKU-CNV-002',
                'category_slug' => 'conveyor',
                'brand_slug' => 'indomesin-teknologi',
                'unit' => 'Set',
                'price' => 35000000,
                'cost_price' => 24500000,
                'selling_price' => 35000000,
                'weight' => 400,
                'width' => 40, 'length' => 600, 'height' => 100,
                'power' => '5500 Watt',
                'capacity' => '10 ton/jam',
                'material' => 'Stainless Steel',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Conveyor screw untuk pengangkutan material bubuk dan granular secara vertikal.',
                'short_description' => 'Screw conveyor 6m untuk material bubuk',
            ],
            [
                'name' => 'Conveyor Roller Gravity',
                'sku' => 'SKU-CNV-003',
                'category_slug' => 'conveyor',
                'brand_slug' => 'indomesin-teknologi',
                'unit' => 'Set',
                'price' => 15000000,
                'cost_price' => 10500000,
                'selling_price' => 15000000,
                'weight' => 200,
                'width' => 50, 'length' => 500, 'height' => 60,
                'power' => '-',
                'capacity' => '2 ton/jam',
                'material' => 'Besi',
                'warranty' => 'Garansi 1 Tahun',
                'warranty_period' => 12,
                'description' => 'Conveyor roller gravity tanpa motor untuk perpindahan barang secara manual dengan bantuan gravitasi.',
                'short_description' => 'Gravity roller conveyor 5m',
            ],

            // Mesin Farmasi
            [
                'name' => 'Mesin Tablet Press 16 Punch',
                'sku' => 'SKU-FRM-001',
                'category_slug' => 'mesin-farmasi',
                'brand_slug' => 'biopharm-machinery',
                'unit' => 'Unit',
                'price' => 125000000,
                'cost_price' => 87500000,
                'selling_price' => 125000000,
                'weight' => 600,
                'width' => 80, 'length' => 100, 'height' => 160,
                'power' => '5500 Watt',
                'capacity' => '40000 tablet/jam',
                'material' => 'Stainless Steel 316',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Mesin tablet press 16 punch untuk produksi tablet farmasi kapasitas 40.000 tablet per jam.',
                'short_description' => 'Tablet press 16 punch, 40rb tablet/jam',
            ],
            [
                'name' => 'Mesin Mixer Farmasi V-Type',
                'sku' => 'SKU-FRM-002',
                'category_slug' => 'mesin-farmasi',
                'brand_slug' => 'biopharm-machinery',
                'unit' => 'Unit',
                'price' => 65000000,
                'cost_price' => 45500000,
                'selling_price' => 65000000,
                'weight' => 350,
                'width' => 100, 'length' => 120, 'height' => 150,
                'power' => '3000 Watt',
                'capacity' => '100 liter',
                'material' => 'Stainless Steel 316',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Mixer V-Type untuk pencampuran serbuk farmasi secara homogen. Kapasitas 100 liter.',
                'short_description' => 'V-mixer 100L untuk serbuk farmasi',
            ],
            [
                'name' => 'Mesin Pengisi Kapsul Semi Otomatis',
                'sku' => 'SKU-FRM-003',
                'category_slug' => 'mesin-farmasi',
                'brand_slug' => 'biopharm-machinery',
                'unit' => 'Unit',
                'price' => 35000000,
                'cost_price' => 24500000,
                'selling_price' => 35000000,
                'weight' => 60,
                'width' => 50, 'length' => 70, 'height' => 80,
                'power' => '500 Watt',
                'capacity' => '5000 kapsul/jam',
                'material' => 'Stainless Steel 304',
                'warranty' => 'Garansi 2 Tahun',
                'warranty_period' => 24,
                'description' => 'Mesin pengisi kapsul semi otomatis untuk produksi obat herbal dan farmasi.',
                'short_description' => 'Pengisi kapsul 5000/jam semi otomatis',
            ],

            // Sparepart
            [
                'name' => 'Belt Conveyor Rubber 100mm',
                'sku' => 'SKU-SPR-001',
                'category_slug' => 'sparepart',
                'brand_slug' => 'indomesin-teknologi',
                'unit' => 'Meter',
                'price' => 150000,
                'cost_price' => 105000,
                'selling_price' => 150000,
                'weight' => 2,
                'width' => 10, 'length' => 100, 'height' => 0.5,
                'power' => '-',
                'capacity' => '-',
                'material' => 'Karet',
                'warranty' => null,
                'warranty_period' => null,
                'description' => 'Belt conveyor rubber lebar 100mm untuk penggantian conveyor belt yang aus.',
                'short_description' => 'Belt conveyor rubber 100mm per meter',
            ],
            [
                'name' => 'Bearing Pillow Block UCP205',
                'sku' => 'SKU-SPR-002',
                'category_slug' => 'sparepart',
                'brand_slug' => 'indomesin-teknologi',
                'unit' => 'Pcs',
                'price' => 75000,
                'cost_price' => 52500,
                'selling_price' => 75000,
                'weight' => 0.5,
                'width' => 5, 'length' => 5, 'height' => 5,
                'power' => '-',
                'capacity' => '-',
                'material' => 'Besi & Karet',
                'warranty' => null,
                'warranty_period' => null,
                'description' => 'Bearing pillow block UCP205 untuk berbagai aplikasi mesin industri.',
                'short_description' => 'Pillow block bearing UCP205',
            ],
            [
                'name' => 'Nozzle Spray SS 1/4 Inch',
                'sku' => 'SKU-SPR-003',
                'category_slug' => 'sparepart',
                'brand_slug' => 'indomesin-teknologi',
                'unit' => 'Pcs',
                'price' => 35000,
                'cost_price' => 24500,
                'selling_price' => 35000,
                'weight' => 0.1,
                'width' => 1, 'length' => 3, 'height' => 1,
                'power' => '-',
                'capacity' => '-',
                'material' => 'Stainless Steel',
                'warranty' => null,
                'warranty_period' => null,
                'description' => 'Nozzle spray stainless steel 1/4 inch untuk sistem pembersihan dan spray industri.',
                'short_description' => 'Nozzle spray SS 1/4 inch',
            ],
        ];

        foreach ($products as $data) {
            $product = Product::firstOrCreate(
                ['sku' => $data['sku']],
                [
                    'category_id' => $categoryIds[$data['category_slug']] ?? null,
                    'brand_id' => $brandIds[$data['brand_slug']] ?? null,
                    'unit_id' => $unitIds[$data['unit']] ?? null,
                    'name' => $data['name'],
                    'slug' => str($data['name'])->slug(),
                    'sku' => $data['sku'],
                    'description' => $data['description'] ?? null,
                    'short_description' => $data['short_description'] ?? null,
                    'price' => $data['selling_price'],
                    'cost_price' => $data['cost_price'],
                    'selling_price' => $data['selling_price'],
                    'weight' => $data['weight'] ?? 0,
                    'width' => $data['width'] ?? 0,
                    'length' => $data['length'] ?? 0,
                    'height' => $data['height'] ?? 0,
                    'power' => $data['power'] ?? null,
                    'capacity' => $data['capacity'] ?? null,
                    'material' => $data['material'] ?? null,
                    'warranty' => $data['warranty'] ?? null,
                    'warranty_period' => $data['warranty_period'] ?? null,
                    'is_active' => true,
                    'status' => 'active',
                    'is_featured' => in_array($data['sku'], ['SKU-MKM-001', 'SKU-PKG-002', 'SKU-BLR-001', 'SKU-GEN-001']),
                ]
            );

            // Create main image for each product
            ProductImage::firstOrCreate(
                ['product_id' => $product->id, 'is_primary' => true],
                [
                    'image_path' => 'products/' . $product->sku . '.jpg',
                    'alt_text' => $data['name'],
                    'sort_order' => 0,
                    'is_primary' => true,
                ]
            );
        }
    }
}
