@extends('errors.layout')
@section('icon', '🔍')
@section('code', '404')
@section('title', 'Page Not Found')
@section('message', 'The page you are looking for does not exist or has been moved. Please check the URL or navigate back to the dashboard.')
