@extends('errors.layout')
@section('icon', '⏰')
@section('code', '419')
@section('title', 'Session Expired')
@section('message', 'Your session has expired due to inactivity. Please refresh the page and log in again to continue.')
