@extends('errors.layout')
@section('icon', '🛑')
@section('code', '429')
@section('title', 'Too Many Requests')
@section('message', 'You have made too many requests in a short period. Please wait a moment before trying again.')
